# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

gems:             [ jekyll-paginate, jekyll-email-protect ]

# Setup
title:            'EOS'
tagline:          'A HEP program for flavor physics'
description:      ''
url:              http://project.het.physik.tu-dortmund.de/eos

paginate:         5

github:
  repo:           https://github.com/eos/eos/

packagecloud:
  repo:           https://packagecloud.io/eos

travisci:
  repo:           https://travis-ci.org/eos/eos

coveralls:
  repo:           https://coveralls.io/github/eos/eos
  badge:          https://coveralls.io/repos/github/eos/eos/badge.svg

doi:              10.5281/zenodo.3376590
